# Generated by Django 2.1.4 on 2019-07-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜品id')),
                ('food_name', models.CharField(max_length=128, unique=True, verbose_name='菜品名字')),
                ('food_info', models.CharField(max_length=1024, null=True, verbose_name='菜品介绍')),
                ('food_make', models.CharField(max_length=2048, null=True, verbose_name='菜品做法')),
                ('food_img', models.CharField(max_length=128, null=True, verbose_name='菜品图片')),
                ('click_num', models.IntegerField(default=0, verbose_name='菜品点击数')),
                ('collect_num', models.IntegerField(default=0, verbose_name='菜品收藏量')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Food')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(verbose_name='用户浏览时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='食谱id')),
                ('menu_name', models.CharField(max_length=64, null=True, verbose_name='食谱名称')),
            ],
        ),
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Food')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective', models.BooleanField(default=True, verbose_name='是否有效')),
                ('menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签id')),
                ('tag_name', models.CharField(max_length=32, unique=True, verbose_name='标签名字')),
                ('effective', models.BooleanField(default=True, verbose_name='是否有效')),
                ('click_num', models.IntegerField(default=0, verbose_name='标签点击数')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id,主键')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='用户名,账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('tel', models.CharField(max_length=13, null=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=32, null=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=3, verbose_name='性别')),
                ('birth', models.DateField(null=True, verbose_name='生日')),
                ('register_time', models.DateTimeField(verbose_name='注册时间')),
                ('last_login', models.DateTimeField(verbose_name='最后登录时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_num', models.IntegerField(default=0, verbose_name='标签点击次数')),
                ('collect_num', models.IntegerField(default=0, verbose_name='标签收藏数')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
        migrations.AddField(
            model_name='menutag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag'),
        ),
        migrations.AddField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
        migrations.AddField(
            model_name='foodtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Tag'),
        ),
        migrations.AddField(
            model_name='collect',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Food'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
